package com.onatsubasi.finalcase.promotion.presentation.controller;

import com.onatsubasi.finalcase.common.core.response.ApiResponse;
import com.onatsubasi.finalcase.common.core.response.ErrorResponse;
import com.onatsubasi.finalcase.promotion.application.dto.internal.CancelPromotionUsageRequest;
import com.onatsubasi.finalcase.promotion.application.dto.internal.PromotionQuoteRequest;
import com.onatsubasi.finalcase.promotion.application.dto.internal.RedeemPromotionUsageRequest;
import com.onatsubasi.finalcase.promotion.application.dto.internal.ReservePromotionUsageRequest;
import com.onatsubasi.finalcase.promotion.application.dto.response.PromotionQuoteResponse;
import com.onatsubasi.finalcase.promotion.application.dto.response.PromotionUsageReservationResponse;
import com.onatsubasi.finalcase.promotion.application.service.PromotionQuoteService;
import com.onatsubasi.finalcase.promotion.application.service.PromotionUsageReservationService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.headers.Header;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.UUID;

@RequiredArgsConstructor
@RestController
@RequestMapping("/internal/promotions")
@Tag(name = "Internal Promotions", description = "Internal promotion quote and usage reservation endpoints for Checkout Service")
public class InternalPromotionController {

    private static final String IDEMPOTENCY_KEY_HEADER = "Idempotency-Key";

    private final PromotionQuoteService promotionQuoteService;
    private final PromotionUsageReservationService reservationService;

    @Operation(
            summary = "Quote promotions",
            description = "Calculates eligible promotions without mutating usage counters. This endpoint is read-only."
    )
    @io.swagger.v3.oas.annotations.responses.ApiResponses({
            @io.swagger.v3.oas.annotations.responses.ApiResponse(
                    responseCode = "200",
                    description = "Promotion quote calculated successfully"
            ),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(
                    responseCode = "400",
                    description = "Invalid quote request",
                    content = @Content(schema = @Schema(implementation = ErrorResponse.class))
            )
    })
    @PostMapping("/quote")
    public ResponseEntity<ApiResponse<PromotionQuoteResponse>> quote(
            @Valid @RequestBody PromotionQuoteRequest request
    ) {
        PromotionQuoteResponse response = promotionQuoteService.quote(request);

        return ResponseEntity.ok(
                ApiResponse.success("Promotion quote calculated successfully", response)
        );
    }

    @Operation(
            summary = "Reserve promotion usage",
            description = "Reserves promotion/coupon usage for checkout. Mutates reserved usage counters. Requires Idempotency-Key."
    )
    @io.swagger.v3.oas.annotations.responses.ApiResponses({
            @io.swagger.v3.oas.annotations.responses.ApiResponse(
                    responseCode = "200",
                    description = "Promotion usage reserved or existing idempotent reservation returned",
                    headers = @Header(name = IDEMPOTENCY_KEY_HEADER, description = "Required idempotency key")
            ),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(
                    responseCode = "400",
                    description = "Invalid reservation request",
                    content = @Content(schema = @Schema(implementation = ErrorResponse.class))
            ),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(
                    responseCode = "409",
                    description = "Usage limit exceeded or idempotency conflict",
                    content = @Content(schema = @Schema(implementation = ErrorResponse.class))
            )
    })
    @PostMapping("/usage-reservations")
    public ResponseEntity<ApiResponse<PromotionUsageReservationResponse>> reserve(
            @Parameter(description = "Idempotency key generated by Checkout Service")
            @RequestHeader(value = IDEMPOTENCY_KEY_HEADER, required = false) String idempotencyKey,

            @Valid @RequestBody ReservePromotionUsageRequest request
    ) {
        PromotionUsageReservationResponse response = reservationService.reserve(
                idempotencyKey,
                request
        );

        return ResponseEntity.ok(
                ApiResponse.success("Promotion usage reserved successfully", response)
        );
    }

    @Operation(
            summary = "Get promotion usage reservation",
            description = "Returns promotion usage reservation details."
    )
    @GetMapping("/usage-reservations/{reservationId}")
    public ResponseEntity<ApiResponse<PromotionUsageReservationResponse>> getReservation(
            @Parameter(description = "Promotion usage reservation id")
            @PathVariable UUID reservationId
    ) {
        return ResponseEntity.ok(
                ApiResponse.success(reservationService.getReservation(reservationId))
        );
    }

    @Operation(
            summary = "Redeem promotion usage",
            description = "Redeems reserved promotion usage after payment success. Idempotent for the same order id."
    )
    @PostMapping("/usage-reservations/{reservationId}/redeem")
    public ResponseEntity<ApiResponse<PromotionUsageReservationResponse>> redeem(
            @Parameter(description = "Promotion usage reservation id")
            @PathVariable UUID reservationId,

            @Valid @RequestBody RedeemPromotionUsageRequest request
    ) {
        PromotionUsageReservationResponse response = reservationService.redeem(
                reservationId,
                request
        );

        return ResponseEntity.ok(
                ApiResponse.success("Promotion usage redeemed successfully", response)
        );
    }

    @Operation(
            summary = "Cancel promotion usage reservation",
            description = "Cancels reserved promotion usage after payment failure, checkout failure, customer cancellation, or compensation."
    )
    @PostMapping("/usage-reservations/{reservationId}/cancel")
    public ResponseEntity<ApiResponse<PromotionUsageReservationResponse>> cancel(
            @Parameter(description = "Promotion usage reservation id")
            @PathVariable UUID reservationId,

            @Valid @RequestBody CancelPromotionUsageRequest request
    ) {
        PromotionUsageReservationResponse response = reservationService.cancel(
                reservationId,
                request
        );

        return ResponseEntity.ok(
                ApiResponse.success("Promotion usage cancelled successfully", response)
        );
    }
}