export const API_ROUTES = {
  auth: {
    login: '/api/auth/login',
    register: '/api/auth/register',
    refresh: '/api/auth/refresh',
    logout: '/api/auth/logout',
    changePassword: '/api/auth/change-password',
    logoutAll: '/api/auth/logout-all',
    me: '/api/auth/me',
  },
  products: {
    search: '/api/products/search',
    searchAlias: '/api/search',
    searchFacets: '/api/products/facets',
    byId: (productId: string) => `/api/products/${productId}`,
    reviewsByProductId: (productId: string) => `/api/products/${productId}/reviews`,
    ratingSummaryByProductId: (productId: string) => `/api/products/${productId}/reviews/summary`,
    autocomplete: '/api/products/autocomplete',
  },
  customer: {
    profile: '/api/customer/profile/me',
    addresses: '/api/customer/addresses',
    addressById: (addressId: string) => `/api/customer/addresses/${addressId}`,
    defaultShipping: (addressId: string) => `/api/customer/addresses/${addressId}/default-shipping`,
    defaultBilling: (addressId: string) => `/api/customer/addresses/${addressId}/default-billing`,
    notifications: '/api/customer/notifications',
    notificationUnreadCount: '/api/customer/notifications/unread-count',
    notificationById: (id: string) => `/api/customer/notifications/${id}`,
    notificationRead: (notificationId: string) => `/api/customer/notifications/${notificationId}/read`,
    notificationReadAll: '/api/customer/notifications/read-all',
    reviews: '/api/customer/reviews',
    reviewById: (reviewId: string) => `/api/customer/reviews/${reviewId}`,
    basket: '/api/customer/basket',
    basketItems: '/api/customer/basket/items',
    basketItemById: (itemId: string) => `/api/customer/basket/items/${itemId}`,
    checkoutQuote: '/api/customer/checkout/quote',
    checkoutSubmit: '/api/customer/checkout',
    checkoutMe: '/api/customer/checkout/me',
    checkoutById: (id: string) => `/api/customer/checkout/${id}`,
    payments: '/api/customer/payments',
    paymentById: (id: string) => `/api/customer/payments/${id}`,
    orders: '/api/customer/orders',
    orderById: (orderId: string) => `/api/customer/orders/${orderId}`,
    cancelOrder: (orderId: string) => `/api/customer/orders/${orderId}/cancel`,
    requestReturn: (orderId: string) => `/api/customer/orders/${orderId}/return`,
    preferences: '/api/customer/preferences/me',
    favorites: '/api/customer/favorites',
    favoriteByProductId: (id: string) => `/api/customer/favorites/${id}`,
    productLists: '/api/customer/product-lists',
    productListById: (id: string) => `/api/customer/product-lists/${id}`,
    productListItem: (listId: string) => `/api/customer/product-lists/${listId}/items`,
    productListItemById: (listId: string, prodId: string) => `/api/customer/product-lists/${listId}/items/${prodId}`,
    shipments: '/api/customer/shipments',
    shipmentById: (id: string) => `/api/customer/shipments/${id}`,
    coupons: '/api/customer/coupons',
  },
  admin: {
    products: '/api/admin/products',
    productById: (id: string) => `/api/admin/products/${id}`,
    productActivate: (id: string) => `/api/admin/products/${id}/activate`,
    productSuspend: (id: string) => `/api/admin/products/${id}/suspend`,
    orders: '/api/admin/orders',
    orderById: (id: string) => `/api/admin/orders/${id}`,
    orderByNumber: (num: string) => `/api/admin/orders/number/${num}`,
    cancelOrder: (id: string) => `/api/admin/orders/${id}/cancel`,
    preparingOrder: (id: string) => `/api/admin/orders/${id}/preparing`,
    checkouts: '/api/admin/checkouts',
    checkoutById: (id: string) => `/api/admin/checkouts/${id}`,
    retryFinalization: (id: string) => `/api/admin/checkouts/${id}/retry-finalization`,
    retryCompensation: (id: string) => `/api/admin/checkouts/${id}/retry-compensation`,
    payments: '/api/admin/payments',
    paymentById: (id: string) => `/api/admin/payments/${id}`,
    paymentRefunds: (id: string) => `/api/admin/payments/${id}/refunds`,
    cancelPayment: (id: string) => `/api/admin/payments/${id}/cancel`,
    searchDocuments: '/api/admin/search/documents',
    searchDocumentByProductId: (productId: string) => `/api/admin/search/documents/${productId}`,
    searchReindex: (productId: string) => `/api/admin/search/reindex/${productId}`,
    searchRebuild: '/api/admin/search/rebuild',
    users: '/api/admin/users',
    userById: (id: string) => `/api/admin/users/${id}`,
    userDisable: (id: string) => `/api/admin/users/${id}/disable`,
    userActivate: (id: string) => `/api/admin/users/${id}/activate`,
    promotions: '/api/admin/promotions',
    promotionById: (id: string) => `/api/admin/promotions/${id}`,
    promotionActivate: (id: string) => `/api/admin/promotions/${id}/activate`,
    promotionPause: (id: string) => `/api/admin/promotions/${id}/pause`,
    promotionExpire: (id: string) => `/api/admin/promotions/${id}/expire`,
    brands: '/api/admin/brands',
    brandById: (id: string) => `/api/admin/brands/${id}`,
    brandActivate: (id: string) => `/api/admin/brands/${id}/activate`,
    brandDeactivate: (id: string) => `/api/admin/brands/${id}/deactivate`,
    brandSuspend: (id: string) => `/api/admin/brands/${id}/suspend`,
    categories: '/api/admin/categories',
    categoryById: (id: string) => `/api/admin/categories/${id}`,
    categoryActivate: (id: string) => `/api/admin/categories/${id}/activate`,
    categoryDeactivate: (id: string) => `/api/admin/categories/${id}/deactivate`,
    categorySuspend: (id: string) => `/api/admin/categories/${id}/suspend`,
    coupons: '/api/admin/coupons',
    couponById: (id: string) => `/api/admin/coupons/${id}`,
    couponActivate: (id: string) => `/api/admin/coupons/${id}/activate`,
    couponPause: (id: string) => `/api/admin/coupons/${id}/pause`,
    couponExpire: (id: string) => `/api/admin/coupons/${id}/expire`,
    couponDeactivate: (id: string) => `/api/admin/coupons/${id}/deactivate`,
    couponBatch: '/api/admin/coupons/batch',
    couponAssignments: '/api/admin/coupons/assignments',
    inventoryItems: '/api/admin/inventory/items',
    inventoryByProductId: (id: string) => `/api/admin/inventory/products/${id}`,
    inventoryIncrease: (id: string) => `/api/admin/inventory/products/${id}/increase`,
    inventoryDecrease: (id: string) => `/api/admin/inventory/products/${id}/decrease`,
    inventorySetStock: (id: string) => `/api/admin/inventory/products/${id}/stock`,
    inventoryThreshold: (id: string) => `/api/admin/inventory/products/${id}/low-stock-threshold`,
    inventoryMovements: (id: string) => `/api/admin/inventory/products/${id}/movements`,
    shipments: '/api/admin/shipments',
    shipmentById: (id: string) => `/api/admin/shipments/${id}`,
    shipmentCancel: (id: string) => `/api/admin/shipments/${id}/cancel`,
    shipmentStatus: (id: string) => `/api/admin/shipments/${id}/status`,
    shipmentTracking: (id: string) => `/api/admin/shipments/${id}/tracking`,
    notifications: '/api/admin/notifications',
    notificationById: (id: string) => `/api/admin/notifications/${id}`,
    notificationDirect: '/api/admin/notifications/direct',
    notificationDeliveryRetry: (id: string) => `/api/admin/notifications/deliveries/${id}/retry`,
    notificationTemplates: '/api/admin/notification-templates',
    notificationTemplateActivate: (id: string) => `/api/admin/notification-templates/${id}/activate`,
    notificationTemplateDeactivate: (id: string) => `/api/admin/notification-templates/${id}/deactivate`,
    reviews: '/api/admin/reviews',
    reviewById: (id: string) => `/api/admin/reviews/${id}`,
    reviewApprove: (id: string) => `/api/admin/reviews/${id}/approve`,
    reviewReject: (id: string) => `/api/admin/reviews/${id}/reject`,
    reviewHide: (id: string) => `/api/admin/reviews/${id}/hide`,
    reviewRestore: (id: string) => `/api/admin/reviews/${id}/restore`,
    reviewReports: '/api/admin/review-reports',
    reviewReportById: (id: string) => `/api/admin/review-reports/${id}`,
    reviewReportResolve: (id: string) => `/api/admin/review-reports/${id}/resolve`,
    reviewReportDismiss: (id: string) => `/api/admin/review-reports/${id}/dismiss`,
    couponsByPromotionId: (id: string) => `/api/admin/coupons/promotion/${id}`,
  },
};
