package com.onatsubasi.finalcase.checkout.domain.enums;

public enum CheckoutSagaStepName {
    BASKET_SNAPSHOT_LOADED,
    CATALOG_SNAPSHOTS_LOADED,
    ADDRESS_SNAPSHOT_LOADED,

    PROMOTION_QUOTED,

    INVENTORY_RESERVED,
    PROMOTION_RESERVED,
    ORDER_CREATED,
    PAYMENT_INITIALIZED,

    PAYMENT_SUCCEEDED_RECEIVED,
    PAYMENT_FAILED_RECEIVED,

    INVENTORY_CONFIRMED,
    INVENTORY_RELEASED,

    PROMOTION_REDEEMED,
    PROMOTION_CANCELLED,

    ORDER_MARKED_PAID,
    ORDER_MARKED_PAYMENT_FAILED,
    ORDER_CANCELLED,

    BASKET_MARKED_CHECKED_OUT,

    SHIPMENT_CREATED,

    CHECKOUT_COMPLETED,
    CHECKOUT_FAILED,
    CHECKOUT_COMPENSATION_PENDING,
    CHECKOUT_COMPENSATED,
    CHECKOUT_EXPIRED,
    CHECKOUT_CANCELLED,

    FINALIZATION_RETRY_REQUESTED,
    COMPENSATION_RETRY_REQUESTED,

    FINALIZATION_FAILED,
    COMPENSATION_FAILED
}