global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    project: finalcase
    environment: local

scrape_configs:
  - job_name: finalcase-spring-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - discovery-service:8761
          - api-gateway:8080
          - auth-service:8081
          - user-service:8082
          - catalog-service:8083
          - search-service:8084
          - basket-service:8085
          - inventory-service:8086
          - promotion-service:8087
          - order-service:8088
          - payment-service:8089
          - shipment-service:8090
          - checkout-service:8091
          - notification-service:8092
          - review-service:8093

  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
