package com.onatsubasi.finalcase.inventory.presentation.controller;

import com.onatsubasi.finalcase.common.core.response.ApiResponse;
import com.onatsubasi.finalcase.common.core.response.ErrorResponse;
import com.onatsubasi.finalcase.inventory.application.dto.internal.ConfirmReservationRequest;
import com.onatsubasi.finalcase.inventory.application.dto.internal.ReleaseReservationRequest;
import com.onatsubasi.finalcase.inventory.application.dto.internal.ReserveStockRequest;
import com.onatsubasi.finalcase.inventory.application.dto.response.InventoryItemResponse;
import com.onatsubasi.finalcase.inventory.application.dto.response.ReservationStatusResponse;
import com.onatsubasi.finalcase.inventory.application.dto.response.StockReservationResponse;
import com.onatsubasi.finalcase.inventory.application.service.InventoryAdminService;
import com.onatsubasi.finalcase.inventory.application.service.InventoryReservationService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.headers.Header;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.UUID;

@RequiredArgsConstructor
@RestController
@RequestMapping("/internal/inventory")
@Tag(name = "Internal Inventory", description = "Internal inventory endpoints for Checkout Service")
public class InternalInventoryController {

    private static final String IDEMPOTENCY_KEY_HEADER = "Idempotency-Key";

    private final InventoryReservationService inventoryReservationService;
    private final InventoryAdminService inventoryAdminService;

    @Operation(
            summary = "Reserve stock",
            description = "Atomically reserves stock for a checkout session. Requires Idempotency-Key."
    )

    @io.swagger.v3.oas.annotations.responses.ApiResponse(
            responseCode = "200",
            description = "Stock reserved or existing idempotent reservation returned",
            headers = @Header(name = IDEMPOTENCY_KEY_HEADER, description = "Required idempotency key")
    )
    @io.swagger.v3.oas.annotations.responses.ApiResponse(
            responseCode = "400",
            description = "Invalid reservation request",
            content = @Content(schema = @Schema(implementation = ErrorResponse.class))
    )
    @io.swagger.v3.oas.annotations.responses.ApiResponse(
            responseCode = "409",
            description = "Insufficient stock or idempotency key conflict",
            content = @Content(schema = @Schema(implementation = ErrorResponse.class))
    )
    @PostMapping("/reservations")
    public ResponseEntity<ApiResponse<StockReservationResponse>> reserveStock(
            @Parameter(description = "Idempotency key generated by Checkout Service")
            @RequestHeader(value = IDEMPOTENCY_KEY_HEADER, required = false) String idempotencyKey,

            @Valid @RequestBody ReserveStockRequest request
    ) {
        StockReservationResponse response = inventoryReservationService.reserveStock(
                idempotencyKey,
                request
        );

        return ResponseEntity.ok(
                ApiResponse.success("Stock reserved successfully", response)
        );
    }

    @Operation(
            summary = "Get reservation",
            description = "Returns stock reservation detail by reservation id."
    )

    @io.swagger.v3.oas.annotations.responses.ApiResponse(
            responseCode = "200",
            description = "Reservation returned successfully"
    )
    @io.swagger.v3.oas.annotations.responses.ApiResponse(
            responseCode = "404",
            description = "Reservation not found",
            content = @Content(schema = @Schema(implementation = ErrorResponse.class))
    )
    @GetMapping("/reservations/{reservationId}")
    public ResponseEntity<ApiResponse<StockReservationResponse>> getReservation(
            @Parameter(description = "Stock reservation id")
            @PathVariable UUID reservationId
    ) {
        return ResponseEntity.ok(
                ApiResponse.success(inventoryReservationService.getReservation(reservationId))
        );
    }

    @Operation(
            summary = "Confirm reservation",
            description = "Confirms a reserved stock reservation after payment success. Idempotent for the same order id."
    )

    @io.swagger.v3.oas.annotations.responses.ApiResponse(
            responseCode = "200",
            description = "Reservation confirmed successfully"
    )
    @io.swagger.v3.oas.annotations.responses.ApiResponse(
            responseCode = "409",
            description = "Reservation cannot be confirmed from current state",
            content = @Content(schema = @Schema(implementation = ErrorResponse.class))
    )

    @PostMapping("/reservations/{reservationId}/confirm")
    public ResponseEntity<ApiResponse<ReservationStatusResponse>> confirmReservation(
            @Parameter(description = "Stock reservation id")
            @PathVariable UUID reservationId,

            @Valid @RequestBody ConfirmReservationRequest request
    ) {
        ReservationStatusResponse response = inventoryReservationService.confirmReservation(
                reservationId,
                request
        );

        return ResponseEntity.ok(
                ApiResponse.success("Reservation confirmed successfully", response)
        );
    }

    @Operation(
            summary = "Release reservation",
            description = "Releases a reserved stock reservation after payment failure, checkout failure, cancellation, or timeout compensation."
    )

    @io.swagger.v3.oas.annotations.responses.ApiResponse(
            responseCode = "200",
            description = "Reservation released successfully or already released"
    )
    @io.swagger.v3.oas.annotations.responses.ApiResponse(
            responseCode = "409",
            description = "Confirmed reservation cannot be released",
            content = @Content(schema = @Schema(implementation = ErrorResponse.class))
    )

    @PostMapping("/reservations/{reservationId}/release")
    public ResponseEntity<ApiResponse<ReservationStatusResponse>> releaseReservation(
            @Parameter(description = "Stock reservation id")
            @PathVariable UUID reservationId,

            @Valid @RequestBody ReleaseReservationRequest request
    ) {
        ReservationStatusResponse response = inventoryReservationService.releaseReservation(
                reservationId,
                request
        );

        return ResponseEntity.ok(
                ApiResponse.success("Reservation released successfully", response)
        );
    }

    @Operation(
            summary = "Get inventory item by product id",
            description = "Internal read endpoint for checking current inventory state. This is not a reservation operation."
    )
    @GetMapping("/products/{productId}")
    public ResponseEntity<ApiResponse<InventoryItemResponse>> getInventoryByProductId(
            @Parameter(description = "Catalog product id")
            @PathVariable UUID productId
    ) {
        return ResponseEntity.ok(
                ApiResponse.success(inventoryAdminService.getByProductId(productId))
        );
    }
}