package com.onatsubasi.finalcase.notification.domain.enums;

public enum NotificationType {
    ORDER_CREATED,
    ORDER_PAID,
    ORDER_PAYMENT_FAILED,
    ORDER_CANCELLED,

    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,

    SHIPMENT_CREATED,
    SHIPMENT_SHIPPED,
    SHIPMENT_DELIVERED,
    SHIPMENT_DELIVERY_FAILED,
    SHIPMENT_CANCELLED,
    SHIPMENT_TRACKING_UPDATED,

    COUPON_ASSIGNED,
    PROMOTION_AVAILABLE,
    PROMOTION_EXPIRING_SOON,

    BACK_IN_STOCK,
    LOW_STOCK_ADMIN_ALERT,
    OUT_OF_STOCK_ADMIN_ALERT,

    CHECKOUT_COMPLETED,
    CHECKOUT_FAILED,
    CHECKOUT_FINALIZATION_FAILED_ADMIN_ALERT,

    REVIEW_REQUEST,
    SYSTEM_ALERT
}